version: 0.2

phases:

  install:
    commands:
      - cd lambda
      - npm install

  build:
    commands:
      - npm install
      - mkdir build-output
      - cp -R main.js node_modules/ build-output
      - zip -r lambda_pipeid_${PIPELINE_EXECUTION_ID}_commitid_${CODEBUILD_RESOLVED_SOURCE_VERSION}.zip build-output

  post_build:
    commands:
      - echo "Build completed on `date`"
      - pwd && ls -lha

artifacts:
  files:
    - 'lambda_pipeid_${PIPELINE_EXECUTION_ID}_commitid_${CODEBUILD_RESOLVED_SOURCE_VERSION}.zip'
  base-directory: 'lambda'
  name: archive_commitid_${CODEBUILD_RESOLVED_SOURCE_VERSION}_pipelineid_${PIPELINE_EXECUTION_ID}
  type: CODEPIPELINE