version: 0.2

phases:

  install:
    commands:
      - cd lambda
      - npm install

  build:
    commands:
      - npm run build
      - mkdir build-output
      - cp -R lambda/main.js node_modules/ build-output

  post_build:
    commands:
      - echo "CODEBUILD_RESOLVED_SOURCE_VERSION = ${CODEBUILD_RESOLVED_SOURCE_VERSION}"
      - echo "PIPELINE_EXECUTION_ID = ${PIPELINE_EXECUTION_ID}"
      - echo "Build completed on `date`"
      - pwd
      - ls -lha

artifacts:
  files:
    - '**/*'
  base-directory: 'build-output'
  name: archive_commitid_${CODEBUILD_RESOLVED_SOURCE_VERSION}_pipelineid_${PIPELINE_EXECUTION_ID}
  type: CODEPIPELINE