version: 0.2

phases:

  install:
    commands:
      - cd my-app
      - npm install

  build:
    commands:
      - npm run build

  post_build:
    commands:
      - echo "CODEBUILD_RESOLVED_SOURCE_VERSION = ${CODEBUILD_RESOLVED_SOURCE_VERSION}"
      - echo "PIPELINE_EXECUTION_ID = ${PIPELINE_EXECUTION_ID}"
      - tar -czf archive.tar.gz ./build
      - echo "Build completed on `date`"
      - pwd
      - ls -lha

artifacts:
  files:
    - 'archive.tar.gz build'
  name: archive_commitid_${CODEBUILD_RESOLVED_SOURCE_VERSION}_pipelineid_${PIPELINE_EXECUTION_ID}
  type: CODEPIPELINE